### ISSUE TITLE
Add link to regenerate autologin link

### ISSUE THREAD

**Issue by pacome35220** [x4m3/epi.today#1]
I think you should provide a way to regenerate autologin link, because we are afraid to give you our autologin link

the HTTP request is :
POST https://intra.epitech.eu/admin/autolog/generate?format=json

**Comment by x4m3** [comment]
I'm not storing any information about users, as you can see in [src/auth/auth.ts](https://github.com/x4m3/epi.today/blob/master/src/auth/auth.ts).

Also, when regenerating the autologin link, it might break applications that use the autologin link. On the autologin page on the intranet it's easy to generate a new link.

I don't want to break people's stuff, so I will let the student generate a new autologin link if they want to.

wontfix
